### ISSUE TITLE
Question-1

### ISSUE THREAD

**Issue by aidevveloper** [ycq091044/SafeDrug#20]
![image](https://user-images.githubusercontent.com/57295863/182271723-e62f59bb-8f71-4a5e-867d-0c0b207edd73.png)

Hi @ycq091044, well-done!
I am try to do data processing but different result with that you showed.
Can you tell me what i did wrong?

**Comment by ycq091044** [comment]
Hi @Harry-KIT, thanks for letting us know. I just created a new machine, download all the files, and tried again. The script works file. I can copy my results here.

<img width="618" alt="image" src="https://user-images.githubusercontent.com/22296469/183527289-14f9d061-477d-4966-9056-0baf399946f0.png">

From your results, the number of patients, procedures, medication, and diagnosis codes is significantly less. Did you make any local changes?

**Comment by aidevveloper** [comment]
Hi @ycq091044, thank you for your reply. I think error is with csv files that i used. i mean that you mentioned to download mimic datasets with the certificate. But I downloaded them without certificate directly from the following sites.

1)https://physionet.org/content/mimiciii-demo/1.4/PRESCRIPTIONS.csv
2)https://physionet.org/content/mimiciii-demo/1.4/DIAGNOSES_ICD.csv
3)https://physionet.org/content/mimiciii-demo/1.4/PROCEDURES_ICD.csv

maybe they differ from those that you mentioned?

**Comment by ycq091044** [comment]
Aha. You are using "demo" dataset, not the true MIMIC-III, just look at the path name "mimiciii-demo". To get the full dataset, please follow the PhysioNet Instruction and get the certificate.
