### ISSUE TITLE
About

### ISSUE THREAD

**Issue by HjZ1998** [ycq091044/SafeDrug#21]
Hello, Thanks for your code! I want to know how to generate the file records_final.pkl with 6350 items in the GitHub repository.
Wait for your responses, Thank you again !

**Comment by ycq091044** [comment]
Hello, could you please refer to data/process.py#384. Run the code and you will get the records.

**Comment by HjZ1998** [comment]
Hello, thank you very much for your reply! The file I obtained after running the process.py only has 267 records, which is different from the existing records_final.pkl file containing 6350 records in the data folder. The numbers of the two do not agree. Therefore, I would like to ask how can you obtain the file containing 6350 records.

**Comment by ycq091044** [comment]
Sorry, did you use the original MIMIC-III or IV data? I only uploaded the sample datasets.

**Comment by HjZ1998** [comment]
I'm using the MIMIC-III data. I want to explore the subject_ID and hadm_ID of these 6350 patients in my work.

**Comment by ycq091044** [comment]
Sorry to reply late. I have been traveling recently.  I will try to reproduce the problem when I come back in 3 days.

**Comment by HjZ1998** [comment]
Ok, thank you. Have a good time！

**Comment by ycq091044** [comment]
Hi @HjZ1998 , I ran the GitHub codes with raw MIMIC-III data. I do obtain 6350 patients as shown below. Could you please show me the statistics after you run `process.py`
<img width="1307" alt="image" src="https://user-images.githubusercontent.com/22296469/211164585-d3eafff6-a1d9-481e-afff-b4ba88862746.png">

**Comment by HjZ1998** [comment]
Sorry, I found out that I was using the wrong three csv files! After I modified this error, the statistics are the same as yours. Very grateful for your help！

**Comment by ycq091044** [comment]
Great to hear that you make it work. Please let me know whether you have other follow-up questions. I will close this issue for now.

**Comment by HjZ1998** [comment]
I have no more questions now, thank you.
