### ISSUE TITLE
Target for trainning and testing

### ISSUE THREAD

**Issue by Data-Designer** [ycq091044/SafeDrug#25]
Hi，我想知道模型的训练和测试是使用患者的最后一次药物还是使用该用户所有用过的药物作为ground truth？
预处理里面似乎使用患者所有用过的药物作为label。

**Comment by ycq091044** [comment]
你好，

在预处理中，我们提取出来每一次visit使用的diagnosis，procedures，和drugs。
<img width="503" alt="image" src="https://github.com/ycq091044/SafeDrug/assets/22296469/fcb73765-f8ef-47a6-8d1c-9b8e3247181c">

在具体模型训练和测试的时候，
- SafeDrug模型会用前N次（包含这次）的diagnosis和procedures作为feature去预测这这次的drug（不是所有的drug）。
- GAMENet模型会用前N次（包含这次）的diagnosis和procedures，以及前N-1次（不包含这次）的drugs作为feature，去预测这这次的drug（不是所有的drug）
- 其他模型有其他的方式，但是最终预测的是这一次的drug set。

**Comment by ycq091044** [comment]
I will close the issue. Welcome to re-open it if you have further questions.
