### ISSUE TITLE
The link expired.

### ISSUE THREAD

**Issue by 137315198** [ycq091044/SafeDrug#26]
Hi, the link that drugbank_drugs_info.csv: drug information table downloaded from drugbank here "https://www.dropbox.com/s/angoirabxurjljh/drugbank_drugs_info.csv?dl=0" expired.

**Comment by ycq091044** [comment]
Sorry for the late response. Could you check this link https://drive.google.com/file/d/1EzIlVeiIR6LFtrBnhzAth4fJt6H_ljxk/view?usp=sharing. I just uploaded my copy.

**Comment by 137315198** [comment]
Thanks!
