### ISSUE TITLE
Missing input data

### ISSUE THREAD

**Issue by yanting14122** [ycq091044/SafeDrug#29]
I can't find the drugbank_info.csv data for the preprocessing, which is supposed to be in 'data/input/' directory. 

Could you please provide the file for the codes to produce the file? Thank you so much.

**Comment by ycq091044** [comment]
Please check the link provided. The file is too large to be uploaded on GitHub.

https://drive.google.com/file/d/1EzIlVeiIR6LFtrBnhzAth4fJt6H_ljxk/view?usp=sharing

**Comment by yanting14122** [comment]
Thanks for the prompt response!
