### ISSUE TITLE
Question about the visit order for a single patient

### ISSUE THREAD

**Issue by Gkunnan97** [ycq091044/SafeDrug#5]
Hello, 
I have a question about the data processing procedure written in 'data/processing.py' : for a single patient, how to keep the visit sequence is ordered by the visit time? Because downstream task(medication prediction for the patient's t-th visit) and the longitudinal patient representation module, I think time-ordered visit sequence is necessary. And it should be ordered by the ['ADMITTIME'](https://mimic.mit.edu/docs/iii/tables/admissions/#admittime-dischtime-deathtime)  in admissions table of the mimic-iii dataset.  Maybe I don't understand the code and the mimic-iii dataset enough. Thanks in advance.

**Comment by ycq091044** [comment]
Thanks for asking this question. The patient-level visits are in order!

Please check our processing.py. During preprocessing, the very high-level logic is to merge the diagnosis table, procedure table, and medication table on the patient ID and visit ID. In the MIMIC dataset, the patient ID is "SUBJECT_ID" and the visit ID is "HADM_ID". Please refer to [https://mimic.mit.edu/docs/iii/tables/](https://mimic.mit.edu/docs/iii/tables/)

In line 22, line 73, and line 91, we sort the medication, diagnosis, and procedure tables, separately, by subject and visit order, and then merge them together. Thus, the patient-level visits are guaranteed to be in order.

**Comment by Gkunnan97** [comment]
Thanks for your reply.
But I am still confused with the sort operation.  Because, for a single patient, the order of 'HADM_ID' is not consistent with the visit order. For the patient whose 'SUBJECT_ID' is  17:
`grep ',17,' ADMISSIONS.csv` 
will get:
- 14,17,194023,2134-12-27 07:15:00,2134-12-31 16:05:00,,"ELECTIVE", ...
- 15,17,161087,2135-05-09 14:11:00,2135-05-13 14:40:00,,"EMERGENCY"...   

'HADM_ID' (column 3) and  'ADMITTIME' (column 4) are in reverse order.
Howerver, when 'SUBJECT_ID' is 21,
`grep ',21,' ADMISSIONS.csv`
will get:

- 19,21,109451,2134-09-11 12:17:00,2134-09-24 16:15:00,,"EMERGENCY"...
- 20,21,111970,2135-01-30 20:50:00,2135-02-08 02:08:00,2135-02-08 02:08:00,"EMERGENCY"...

the order of 'HADM_ID' is the same with 'ADMITIME'

So, I thick that it may not be possible to maintain the visit order only by the sort operation with 'HADM_ID'. 
Thanks in advance.
